spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    password: Sachinkaju@1
    url: jdbc:mysql://localhost:3306/project
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
